### ISSUE TITLE
Backplane RevA updates

### ISSUE THREAD

**Issue by bradjc** [lab11/signpost#1]
- [x] Numbers in silkscreen for modules
- [x] Move part labels off of vias (korea is ok when the vias are small, these vias are big)
- [x] Fix U30 package (and the other 5)
- [x] Minimize plane area (?)
- [x] USB data muxes have wrong control signals. Should be fed with `MODn_USB_!EN`, not `MODn_ISO_USB`
- [x] Also, it seems like the unused port should have pull downs: https://e2e.ti.com/support/interface/digital_interface/f/130/p/367935/1295211#1295211
- [x] Pull `!BACKPLANE_RESET` high instead of low
  - [x] ~~Add jumper spot for !backplane_reset to VCC~~
- [x] Fix stubs on USB pull-down resistors (see 4.1 of http://www.usb.org/developers/docs/hs_usb_pdg_r1_0.pdf)
- [x] Update power module for battery / solar attachment
- [x] Add pullup `!OVR` for unused USB port

**Comment by ppannuto** [comment]
- USB data muxes have wrong control signals. Should be fed with `MODn_USB_!EN`, not `MODn_ISO_USB`

**Comment by bradjc** [comment]
I also think we should revisit this somewhat bizarre decision to reset by default. Do we really want the controller to say "If I can't work then nothing can work!!! Muwahahahaha!"?

**Comment by ppannuto** [comment]
It wasn't so malicious as that sounds. The idea behind it was protection of
the system. If the controller resets itself, dies, or w/e, then while the
controller is out of commission a wayward module can't bleed the system
dry.

What would you prefer the default behavior to be if there's no active
controller, turn everything on?

**Comment by bradjc** [comment]
In the case that the controller is gonezo, then everything is broken and I don't think it matters what happens. But in case that controller resets briefly, everything would break, even in the case the controller comes back in a few milliseconds. Things like USB to linux, and I2C to radio can all keep happening while the controller resets. And the power supply should still be aggregating the energy of each module.

**Comment by ppannuto** [comment]
That's almost already the situation.

Because all of the modules are on GPIO extenders, they wouldn't change state when the controller goes away. The missing bit is that `!BACKPLANE_RESET` will trip because the controller isn't holding it any more (which will then cause all the GPIO extenders to reset).

Perhaps the right solution then is to latch/buffer `!BACKPLANE_RESET` the same way. That way the signpost still "boots up" to a sane state when all power is lost, but if the controller disappears for a bit things will keep on keeping on (and the controller can read all the GPIO extenders to learn the state on reset).

**Comment by bradjc** [comment]
What about just pulling !RESET high and calling it a day? Who knows what state everything is in during reset, but everything should be fine in the default, just resetted state. The controller can reset everything if it wants. All the modules will still default to disabled.

Also, it seems like the unused port should have pull downs: https://e2e.ti.com/support/interface/digital_interface/f/130/p/367935/1295211#1295211

**Comment by ppannuto** [comment]
Currently, the debug LEDs for the backplane live in the corner on each module, but are covered by the backplane case when it's installed. 

The original thoughts for this were
- You likely won't populate the debug LEDs on a deployed board b/c they burn power
- There are no components anywhere under modules so module creators can consider the full vertical space under the module as theirs

Thinking more
- It sucks a little that you don't have the option for debug LEDs and case
- It's unlikely that an smd LED and an 0603 resistor are going to break the bank for vertical space for module makers (though it does become something they may have to think about in corner cases)

I'm leaning towards moving these more in the middle of the module space but wanted to see if anyone thought that was a terrible idea for some reason

**Comment by bradjc** [comment]
At first I was opposed to this, then for it, and now I'm against it again. While I agree having the LEDs visible inside the case would be useful (particularly for a demo), they are only useful for populated modules, but once the module is populated you won't be able to see the LEDs anymore.

**Comment by ppannuto** [comment]
Yeah, that's the same back and forth I went through the first time. Eventually concluded that having unpopulated parts visible wasn't a great aesthetic, happy to leave that conclusion.

**Comment by ppannuto** [comment]
@adkinsjd can you send me any hole / mounting / plating requirements for the new power connectors you're looking at? I just need enough dimensions to put holes in the right place on the PCB

**Comment by ppannuto** [comment]
@adkinsjd I removed the jumper terminals and put one hole at `(1.749, 5.751) drill 1.125`.

Do I need to do anything else?

**Comment by ppannuto** [comment]
Most recent commit removes a lot of metal. Hopefully that should make things more manageable.

@bradjc is there anything worth trying to do to the footprint of U20-25 to make that part more solderable? Smaller planes will help, but it's necessarily in the middle of the planes for the USB traces, so there's still non-trivial metal around them.

I think it's about ready to pull the trigger on Rev B
