### ISSUE TITLE
Convert ltc output to uAh and check for i2c errors

### ISSUE THREAD

**Issue by bradjc** [lab11/signpost#14]

**Comment by nealjack** [comment]
What i2c errors are you talking about?

**Comment by bradjc** [comment]
Mostly if the ltc2941 address was NAKed.

**Comment by nealjack** [comment]
Did not see unacked ltc addresses.
Note: what I added works when only the controller and power supply are on the backplane. Had issues last night with the radio module. Adding configuration writes to the ltcs in signpost_energy_init would cause the controller to freeze up. Assuming a yield that never got a callback.
