### ISSUE TITLE
Power Supply Module: update paste layer

### ISSUE THREAD

**Issue by bradjc** [lab11/signpost#15]
Modify the paste layer on the ICs to have a smaller square in the center of the pad instead of the entire pad.

**Comment by ppannuto** [comment]
@nealjack did this get fixed on the current rev?

**Comment by nealjack** [comment]
yeah it's on my list

**Comment by nealjack** [comment]
So which ICs actually have too large squares on the paste layers? Why is it particular to the power module? It seems like a lot of our ICs have huge paste layers.
