### ISSUE TITLE
Backplane RevB updates

### ISSUE THREAD

**Issue by ppannuto** [lab11/signpost#16]
So far just nits but a place to collect things.
- [x] Add a space on silkscreen to write in an identifier (i.e. Backplane no. 12)
- [x] Move `R46` and `R47` to be near `R48`. (Or vice-versa and move the test points too)
- [x] ~Software resettable fuses for modules~
  - Moved to the power module's responsibility
- [x] ~TVS diodes on all module I/O ?~
  - I'm not convinced this is needed, can revisit if stuff actually breaks
- [x] ~Deal with USB Hub Reset problem~
![image](https://cloud.githubusercontent.com/assets/339422/22951767/69ad599a-f2d8-11e6-8211-c6c734981d7f.png)
   - Resolved by adding GPIO extender for reset line control. Debug backplane may still add PoR circuitry, but not really needed for signpost proper

**Comment by adkinsjd** [comment]
- [x] ~I2C bypass jumpers in case the isolators aren't working~
    - more evidence indicates that was really only a problem of the rush solder job on the first round

**Comment by adkinsjd** [comment]
- [x] Large annular rings around all mechanical holes!
- [x] Don't route any traces near mechanical holes

**Comment by bradjc** [comment]
- [x]  ~All traces on middle layers?~
   - From below, not doing this for now. Moved all traces away from the edges and from mount holes where possible

**Comment by adkinsjd** [comment]
- [ ] A generally thicker, more sturdy pcb

**Comment by bradjc** [comment]
If the PCB gets thicker, we have to keep in mind the through-hole parts and make sure they are still solderable.

**Comment by ppannuto** [comment]
- [x] replace GPIO extender package with version from debug backplane

**Comment by brghena** [comment]
- [x] Add GPIO extender to reset / monitor the USB hub

**Comment by ppannuto** [comment]
- [x] Validate all component heights are < 0.080" (for compat w/ thicker pcb)
   - tallest component is the big USB cap, coming in at 0.075"

**Comment by ppannuto** [comment]
> All traces on middle layers?

Where are we at on this - superfluous or worth the effort? I kinda don't want to do it just because it'll take a while to do, but if it's worth it I will

**Comment by brghena** [comment]
I think it's unnecessary

**Comment by adkinsjd** [comment]
I think as long as you are especially careful to keep traces away from
screws and edges you are fine. The removal of internal module seals should
make this even less of an issue

**Comment by ppannuto** [comment]
I think I've now addressed everything here.

Do we have other changes or additions to the backplane?

**Comment by ppannuto** [comment]
- [x] Connect the watchdog from controller to power module
   - [x] @brghena update controller module in library to add watchdog pin
   - [x] @nealjack update power module in library to add watchdog pin

**Comment by nealjack** [comment]
- [x] Step up the vbat+/- and vsol+- traces to at least 100mil
