### ISSUE TITLE
Radio module reliability

### ISSUE THREAD

**Issue by brghena** [lab11/signpost#19]
We want to improve radio module reliability. This has two prongs: detecting errors and resetting cleanly
1. We want to be able to detect errors on the Nucleum and iM880B. For the Nucleum, the `ble_error` function seems like it should be able to do this. However, while testing I could not seem to get this function to be run... For the iM880, we should read its responses. The console `getauto` function can probably do this adequately. Upon detecting an error, the `app_watchdog_reset_app` function can be called to reboot the module.
2.  We want the radio board the reliably reset even if the Nucleum or iM880B have gotten into a bad state. The power gate on the Nucleum is toggled at start, getting it into a reliable state. Something needs to be done for the iM880B too. Using its power gate, however, seemed to lead to system problems and was being tested when the iM880 on my radio board gave up the ghost, leading to worries on my part that it might have been doing bad things for the board. @adkinsjd suggested there is a reset line that can be used instead.

**Comment by adkinsjd** [comment]
This is fixed. Nulceum fixed by power gate. IM880B software reset.
