### ISSUE TITLE
Controller RevA Updates

### ISSUE THREAD

**Issue by ppannuto** [lab11/signpost#2]
Issue to track fixes for controller RevA
- [x] There are two pins labeled `USB_D+` and none `USB_D-`

**Comment by brghena** [comment]
Other issues with Controller Rev A
- [x] VR1 doesn't have a Pin 1 marker
- [x] L2 & L3 have dots on their package, but not on the silkscreen
- [ ] D1 has basically no markings on it's package and is really hard to tell orientation on
- [x] R11 - R12 silkscreen too close to inductor
- [ ] C25 - C27 component is too tall and doesn't place on the board well
- [x] FB3 - FB4 are too big for their pads
- [x] C25 physically close to inductor

**Comment by ppannuto** [comment]
@brghena when you fix "D1 has basically no markings on it's package and is really hard to tell orientation on", can you poke me to fix on seinduino somehow?

**Comment by brghena** [comment]
- [x] GND pads extremely hard to solder on controller module headers

**Comment by brghena** [comment]
- [x] Need ability to reset GPS

**Comment by brghena** [comment]
- [x] USB_ID connection for Edison is incorrect. Needs to be Grounded in normal case (acts as host) and Floating in programming case (acts as peripheral). (https://www.maximintegrated.com/en/app-notes/index.mvp/id/1822)

**Comment by nealjack** [comment]
- [ ] Edison on controller draws 2x-4x the current of an Edison on the breakout board
- [ ] Controller draws over 100mA on its own. We think it's the GPS
- [x] Power gate GPS
- [x] Power gate everything

**Comment by brghena** [comment]
The vast majority of this has been handled in Control Module rev B (ca164b0e88493279cb7291171baee575391ca474)

The issues with D1 and C25-C27 have been ignored. The large power draw of the Edison will be further investigated when the new board is complete
