### ISSUE TITLE
Summon demo app

### ISSUE THREAD

**Issue by brghena** [lab11/signpost#20]
Thomas added a summon app which can be viewed at [j2x.us/signp](http://j2x.us/signp). This issue is for tracking updates that are needed for it. @tzachari 
- [x] Add time and date to the `Controller` view
- [x] Add the UC Berkeley logo to the signpost
- [x] Either add the UCSD logo to the `Air Quality` view or rename to `UCSD Air Quality`
- [x] Make `SIGNPOST` name bigger. Might have to move it

**Comment by ppannuto** [comment]
- [x] Resolve mixed security content

The j2x url currently redirects to https rawgit, but the websocket uri isn't over secured websockets. Manually going to the http version of the rawgit page allows the websocket to connect, but this should be consistent.

![screen shot 2016-10-23 at 16 17 14](https://cloud.githubusercontent.com/assets/339422/19629150/32e89096-993c-11e6-9936-0848ae1220a6.png)

**Comment by brghena** [comment]
- [x] the '2' in 'CO2' doesn't load right on android

-> note, works fine on iOS -Pat

![screenshot_2016-10-23-17-17-40](https://cloud.githubusercontent.com/assets/235448/19629521/d98d2c24-9944-11e6-912a-8e29f2eb37f6.png)

**Comment by bradjc** [comment]
- [x] add controller energy to power supply box
