### ISSUE TITLE
Controller Rev B Fixes

### ISSUE THREAD

**Issue by brghena** [lab11/signpost#22]
List for tracking problems discovered with Rev B of the controller

 - [x] Swap C12 and C25 locations

**Comment by brghena** [comment]
- [x] Clearance on Edison mounting holes is insufficient
- [x] Pull-up on LINUX_ENABLE_POWER is not working

**Comment by ppannuto** [comment]
- [x] Connect !BACKPLANE_RESET to a SAM4L

**Comment by ppannuto** [comment]
- [x] Label the usb ports on the *top* of the board

**Comment by brghena** [comment]
- [ ] Better isolation for things touching the Linux power domain
- [x] Mod_in/out pins for the Storage Master too

**Comment by ppannuto** [comment]
- [x] connect module i2c (and may as well do smbus while we're at it) pins to gpio inputs as well so controller can monitor

**Comment by ppannuto** [comment]
- [x] PPS should also be input to controller (and storage master while we're at it)

**Comment by brghena** [comment]
- [x] Interrupt pin to the Edison

**Comment by brghena** [comment]
- [x] Interrupt pin from Storage Master to Controller

**Comment by adkinsjd** [comment]
- [x] Individual reset buttons for each MCU

**Comment by adkinsjd** [comment]
- [x] Add POR chips for both SAM4Ls. Backplane power nets are too large to fulfill necessary voltage rise rates, meaning SAM4Ls need POR.
