### ISSUE TITLE
Ambient Rev C fixes

### ISSUE THREAD

**Issue by brghena** [lab11/signpost#29]
Tracking things to fix for the next revision:

- [x] Grounded mounting holes
- [x] Silkscreen labels on header pins
- [ ] ~~Change to 0402 ferrite bead~~
- [x] Remove extraneous pressure sensors. We can't even purchase all of them anymore

**Comment by ppannuto** [comment]
- [x] Check that caps are on `VDDCORE` not `VDDOUT`
