### ISSUE TITLE
Receive LoRa packets in node.js environment

### ISSUE THREAD

**Issue by bradjc** [lab11/signpost#9]

**Comment by srohrer32** [comment]
npm: https://www.npmjs.com/package/iM880-serial-comm

git repo: https://github.com/lab11/LoRa-comms

**Comment by bradjc** [comment]
It might be good to rename the LoRa-comms repo (to match the npm package) and have it only contain the node library. A one-to-one mapping makes it easier to find and update in the future.

**Comment by srohrer32** [comment]
New repo here: https://github.com/lab11/iM880-serial-comm . The npm package also now points to the new repo.
